name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Get build number
      id: build_number
      run: echo "::set-output name=build_number::$(date +%s)"

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_REGISTRY }}/sanwu/zhaoxi-msacormmerce-portal:${{ steps.build_number.outputs.build_number }} .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_REGISTRY }}/sanwu/zhaoxi-msacormmerce-portal:${{ steps.build_number.outputs.build_number }}
